// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMa-9vVeeaxT_1M8JMEDJAQi7ucZEXiio',
    appId: '1:821476537606:web:4ce30d41d8489944f2da87',
    messagingSenderId: '821476537606',
    projectId: 'vegshop-b1593',
    authDomain: 'vegshop-b1593.firebaseapp.com',
    storageBucket: 'vegshop-b1593.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_7pTw_pOiTIkKGIeGw3JimRK_eKuq6Ns',
    appId: '1:821476537606:android:90e69683d5610207f2da87',
    messagingSenderId: '821476537606',
    projectId: 'vegshop-b1593',
    storageBucket: 'vegshop-b1593.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzheQyxrOv1ZeCmb3LWk3ik4it7ATUBp4',
    appId: '1:821476537606:ios:29f0cd2aeee6ffb4f2da87',
    messagingSenderId: '821476537606',
    projectId: 'vegshop-b1593',
    storageBucket: 'vegshop-b1593.appspot.com',
    iosBundleId: 'com.example.vegshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzheQyxrOv1ZeCmb3LWk3ik4it7ATUBp4',
    appId: '1:821476537606:ios:79bb484311c8b925f2da87',
    messagingSenderId: '821476537606',
    projectId: 'vegshop-b1593',
    storageBucket: 'vegshop-b1593.appspot.com',
    iosBundleId: 'com.example.vegshop.RunnerTests',
  );
}
