import 'package:flutter/material.dart';
import 'package:vegshop/Widgets/widgets.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/',
      routes: {
        '/': (context) => Home(),
        '/aboutUs': (context) => AboutUs(),
        '/contactUs': (context) => ContactUs(),
        '/shop': (context) => Shop(),
        '/berry': (context) => Berry(),
        '/veg': (context) => Veg(),
        '/fruit': (context) => Fruit(),
        '/login': (context) => Login(),
        '/cart': (context) => Cart(),
        '/map': (context) => MapScreen(),
        '/tomato': (context) {
          // Extracting arguments passed to the route
          final args = ModalRoute.of(context)?.settings.arguments;
          print(args);
          if (args is String) {
            // If the argument is a string, pass it to the Tomato widget
            return Tomato(name: args);
          } else {
            // Handle if no or invalid arguments are provided
            return Container(); // You can return an error screen or handle it as you prefer
          }
        },
      },
    );
  }
}
